/** İşlem geçmişine yazılırken istek gövdesinden alınan (gizli olmayan) alanlar */
export const AUDIT_BODY_FIELDS = [
  'action',
  'amount',
  'approvedAmount',
  'note',
  'reason',
  'role',
  'canSell',
  'transferRef',
  'status',
  'resolution',
  'isEnabled',
  'testMode',
  'feePercent',
  'feeFixed',
  'minAmount',
  'maxAmount',
  'name',
  'commissionRate',
  'permissions',
  'defaultSalePercent',
  'withdrawalPercent',
  'withdrawalFixed',
  'host',
  'port',
  'enabled',
  'audience',
  'email',
  'title',
  'sendEmail',
] as const;
